name: CI-CD
on:
  push: 
    branches: [main]
jobs: 
  build: 
    runs-on: self-hosted
    steps: 
    - run: |
        cd /var/www/MVCH-Graph-1
        git pull origin main
        composer install
        cd /var/www/MVCH-Graph-2
        git pull origin main
        composer install
        cd /var/www/MVCH-Graph-3
        git pull origin main
        composer install
